In [1]:
import json
import pandas as pd

In [ ]:

json_path = "/data/2_data_server/cv-07/dice/2025_samsung_challenge/dataset/visual7w_2/nocap/nocaps_test_image_info.json"

In [3]:
with open(json_path, "r") as f:
    data = json.load(f)

In [4]:
data[0]

{'image_path': '/data/2_data_server/cv-07/dice/2025_samsung_challenge/dataset/visual7w_2/test_2014/TEST_245.jpg',
 'text_segment': None,
 'image_id': 60}

In [5]:
csv_path = "/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_coco_captioning_inference/eval_results.csv"

df = pd.read_csv(csv_path)

df.head()

df["caption"]

0      A group of people standing around a table in a...
1         A young man dives for a volleyball on a court.
2      A large jetliner flying through the sky above ...
3        A man standing on a balcony overlooking a pool.
4                  A view of a city skyline from a park.
                             ...
847    A sailboat in the middle of a body of water at...
848    A man sitting on a couch holding a bowl of chips.
849    A train station with a clock tower in the back...
850         A large group of people shopping in a store.
851     A row of flower pots sitting outside of a house.
Name: caption, Length: 852, dtype: object

In [8]:
df['image_path'] = ''

In [9]:
df.head()

   image_id                                            caption image_path
0         0  A group of people standing around a table in a...
1         1     A young man dives for a volleyball on a court.
2         2  A large jetliner flying through the sky above ...
3         3    A man standing on a balcony overlooking a pool.
4         4              A view of a city skyline from a park.

In [10]:
for item in data:
    image_id = item["image_id"] - 60
    # csv image id에 맞는 행에 image path 추가
    df.loc[df["image_id"] == image_id, "image_path"] = item["image_path"]

In [11]:
df.head()

,image_id,caption,image_path
0,0,A group of people standing around a table in a...,/data/2_data_server/cv-07/dice/2025_samsung_ch...
1,1,A young man dives for a volleyball on a court.,/data/2_data_server/cv-07/dice/2025_samsung_ch...
2,2,A large jetliner flying through the sky above ...,/data/2_data_server/cv-07/dice/2025_samsung_ch...
3,3,A man standing on a balcony overlooking a pool.,/data/2_data_server/cv-07/dice/2025_samsung_ch...
4,4,A view of a city skyline from a park.,/data/2_data_server/cv-07/dice/2025_samsung_ch...

In [ ]:
# save th csv file

df.to_csv(csv_output_path, index=False)

In [2]:
csv_path_1 = "/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_coco_captioning_inference/eval_results_with_image_path.csv"
csv_path_2 = "/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_coco_captioning_inference/test.csv"

In [4]:
# csv 2에 image path가 같으면 csv_1의 caption을 추가
df_1 = pd.read_csv(csv_path_1)
df_2 = pd.read_csv(csv_path_2)
df_2['caption'] = ''

for i, row in df_2.iterrows():
    matching_row = df_1[df_1['image_path'] == row['img_path']]
    if not matching_row.empty:
        df_2.at[i, 'caption'] = matching_row.iloc[0]['caption']
df_2.head()

,ID,img_path,Question,A,B,C,D,caption
0,TEST_000,./test_input_images/TEST_000.jpg,What types of fruits are visible in the image?,Bananas and grapes placed in baskets,Apples and oranges displayed on the counter,Peaches and plums in a wooden crate,Pears and lemons arranged neatly,"Apples, oranges, and other fruits are on displ..."
1,TEST_001,./test_input_images/TEST_001.jpg,What type of cuisine are these dishes most com...,"Chinese, famous for dumplings and noodles.","Mexican, featuring tacos and enchiladas.","Italian, known for pasta dishes and pizzas.","Indian, rich in spices and curries.",A pot full of dumplings being cooked on a stove.
2,TEST_002,./test_input_images/TEST_002.jpg,What is a common reason people doing this acti...,For attending concerts in open-air settings,For physical exercise and scenic views of the ...,For shopping opportunities in remote locations,For fishing in mountain streams,A woman sitting on top of a mountain drinking ...
3,TEST_003,./test_input_images/TEST_003.jpg,"What type of clothing are the people wearing, ...","Light clothing, suggesting a warm and sunny cl...","Swimwear, suggesting a tropical and beach-like...","Heavy coats, suggesting a cold and possibly sn...","Raincoats, suggesting rainy and wet weather co...",A large group of people boarding a cruise ship.
4,TEST_004,./test_input_images/TEST_004.jpg,What might the woman have done just before thi...,Landing from a jump or completing a spin in th...,Practiced her routine several times to perfect...,Chatting with other skaters at the boards near...,Sitting down on the ice to take a break and rest.,A woman in a pink dress is jumping on a rink.

In [6]:
output_path = "/data/2_data_server/cv-07/dice/2025_samsung_challenge/finetuning/unilm/beit3/output_coco_captioning_inference/test_with_caption.csv"

In [7]:
df_2.to_csv(output_path, index=False)